In [69]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [70]:
!wget https://github.com/kaopanboonyuen/Python-Data-Science/raw/master/Dataset/hed2020_dataset.csv hed_dataset.csv

--2023-02-05 09:38:45--  https://github.com/kaopanboonyuen/Python-Data-Science/raw/master/Dataset/hed2020_dataset.csv
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kaopanboonyuen/Python-Data-Science/master/Dataset/hed2020_dataset.csv [following]
--2023-02-05 09:38:45--  https://raw.githubusercontent.com/kaopanboonyuen/Python-Data-Science/master/Dataset/hed2020_dataset.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 352588 (344K) [text/plain]
Saving to: ‘hed2020_dataset.csv.1’

hed2020_dataset.csv 100%[===================>] 344.32K  --.-KB/s    in 0.007s

2023-02-05 09:38:45 (50.2 MB/s) - ‘hed2020_dataset.csv.1’ saved [352588/352588]

--2023-02-05 09:38:45--  http://hed_dataset.csv/
Resolving hed_dataset.csv (hed_dataset.csv)... failed: Name or service not known.
wget: unable to resolve host address ‘hed_dataset.csv’
FINISHED --2023-02-05 09:38:45--
Total wall clock time: 0.2s
Downloaded: 1 files, 344K in 0.007s (50.2 MB/s)

In [71]:
df = pd.read_csv('hed2020_dataset.csv')

In [72]:
print ('Shape of hed2020_dataset', df.shape)

Shape of hed2020_dataset (5824, 24)

In [73]:
df.head(5)

,id,label,cap-shape,cap-surface,bruises,odor,gill-attachment,gill-spacing,gill-size,stalk-shape,...,ring-number,ring-type,spore-print-color,population,habitat,cap-color-rate,gill-color-rate,veil-color-rate,stalk-color-above-ring-rate,stalk-color-below-ring-rate
0,1,p,x,s,t,p,f,c,n,e,...,o,p,k,s,u,1.0,3.0,1.0,1.0,1.0
1,2,e,x,s,t,a,f,c,b,e,...,o,p,n,n,g,2.0,3.0,1.0,1.0,1.0
2,3,e,b,s,t,l,f,c,b,e,...,o,p,n,n,m,3.0,1.0,1.0,1.0,1.0
3,4,p,x,y,t,p,f,c,n,e,...,o,p,k,s,u,3.0,1.0,1.0,1.0,1.0
4,5,e,x,s,f,n,f,w,b,t,...,o,e,n,a,g,4.0,3.0,1.0,1.0,1.0

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5824 entries, 0 to 5823
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5824 non-null   int64
 1   label                        5764 non-null   object
 2   cap-shape                    5824 non-null   object
 3   cap-surface                  5797 non-null   object
 4   bruises                      5725 non-null   object
 5   odor                         5725 non-null   object
 6   gill-attachment              5725 non-null   object
 7   gill-spacing                 5694 non-null   object
 8   gill-size                    5703 non-null   object
 9   stalk-shape                  5703 non-null   object
 10  stalk-root                   5793 non-null   object
 11  stalk-surface-above-ring     5793 non-null   object
 12  stalk-surface-below-ring     5793 non-null   object
 13  veil-type                    5762 non-null   object
 14  ring-number                  5762 non-null   object
 15  ring-type                    5762 non-null   object
 16  spore-print-color            5768 non-null   object
 17  population                   5768 non-null   object
 18  habitat                      5793 non-null   object
 19  cap-color-rate               5797 non-null   float64
 20  gill-color-rate              5703 non-null   float64
 21  veil-color-rate              5762 non-null   float64
 22  stalk-color-above-ring-rate  5793 non-null   float64
 23  stalk-color-below-ring-rate  5762 non-null   float64
dtypes: float64(5), int64(1), object(18)
memory usage: 1.1+ MB

In [75]:
df.describe(include = 'all')

,id,label,cap-shape,cap-surface,bruises,odor,gill-attachment,gill-spacing,gill-size,stalk-shape,...,ring-number,ring-type,spore-print-color,population,habitat,cap-color-rate,gill-color-rate,veil-color-rate,stalk-color-above-ring-rate,stalk-color-below-ring-rate
count,5824.000000,5764,5824,5797,5725,5725,5725,5694,5703,5703,...,5762,5762,5768,5768,5793,5797.000000,5703.000000,5762.000000,5793.000000,5762.000000
unique,NaN,2,5,4,2,9,2,2,2,2,...,3,5,8,6,7,NaN,NaN,NaN,NaN,NaN
top,NaN,p,f,y,f,n,f,c,b,t,...,o,p,w,v,d,NaN,NaN,NaN,NaN,NaN
freq,NaN,3660,2397,2517,3849,2235,5518,5234,3663,3282,...,5132,2379,2380,3521,2608,NaN,NaN,NaN,NaN,NaN
mean,2912.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.327411,5.888480,1.019264,2.310375,3.632419
std,1681.388315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.856785,2.812418,0.147220,1.664648,2.370531
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1456.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.000000,4.000000,1.000000,1.000000,1.000000
50%,2912.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.000000,6.000000,1.000000,2.000000,5.000000
75%,4368.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.000000,9.000000,1.000000,3.000000,5.000000
max,5824.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.000000,12.000000,3.000000,9.000000,9.000000

[From step 1] before doing the data prep., how many "na" are there in "gill-size" variables?

In [76]:
nan_count = df['gill-size'].isna().sum()
print("Number of 'na' values in 'gill-size':", nan_count)

Number of 'na' values in 'gill-size': 121

### Pre-processing (EDA)

2. Drop rows where the target (label) variable is missing.

3. Drop the following variables:

'id','gill-attachment', 'gill-spacing', 'gill-size','gill-color-rate',

'stalk-root', 'stalk-surface-above-ring', 'stalk-surface-below-ring', 'stalk-color-above-ring-rate','stalk-color-below-ring-rate','veil-color-rate','veil-type'

4. Examine the number of rows, the number of digits, and whether any are missing.

5. Fill missing values by adding the mean for numeric variables and the mode for nominal variables.

6. Convert the label variable e (edible) to 1 and p (poisonous) to 0 and check the quantity. class0: class1

7. Convert the nominal variable to numeric using a dummy code with drop_first = True.

In [77]:
df = df.dropna(subset=['label'])
df.shape

(5764, 24)

In [78]:
df = df.drop(columns=['id','gill-attachment', 'gill-spacing', 'gill-size','gill-color-rate',
                      'stalk-root', 'stalk-surface-above-ring', 'stalk-surface-below-ring',
                      'stalk-color-above-ring-rate','stalk-color-below-ring-rate','veil-color-rate','veil-type'])
df.shape

(5764, 12)

In [79]:
df.describe(include='all')

,label,cap-shape,cap-surface,bruises,odor,stalk-shape,ring-number,ring-type,spore-print-color,population,habitat,cap-color-rate
count,5764,5764,5737,5665,5665,5643,5702,5702,5708,5708,5733,5737.000000
unique,2,5,4,2,9,2,3,5,8,6,7,NaN
top,p,f,y,f,n,t,o,p,w,v,d,NaN
freq,3660,2382,2492,3843,2178,3225,5072,2324,2380,3491,2555,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.327523
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.859218
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5764 entries, 0 to 5823
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   label              5764 non-null   object
 1   cap-shape          5764 non-null   object
 2   cap-surface        5737 non-null   object
 3   bruises            5665 non-null   object
 4   odor               5665 non-null   object
 5   stalk-shape        5643 non-null   object
 6   ring-number        5702 non-null   object
 7   ring-type          5702 non-null   object
 8   spore-print-color  5708 non-null   object
 9   population         5708 non-null   object
 10  habitat            5733 non-null   object
 11  cap-color-rate     5737 non-null   float64
dtypes: float64(1), object(11)
memory usage: 585.4+ KB

In [81]:
for col in df.columns:
    if col == 'label': continue
    if np.issubdtype(df[col].dtype, np.number) :
        df[col] = df[col].fillna(df[col].mean())
    else: df[col] = df[col].fillna(df[col].mode().max())

In [82]:
for var in df.columns.tolist():
    missing_values = df[var].isna().sum()
    print(var, missing_values)

label 0
cap-shape 0
cap-surface 0
bruises 0
odor 0
stalk-shape 0
ring-number 0
ring-type 0
spore-print-color 0
population 0
habitat 0
cap-color-rate 0

In [83]:
df['label'] = df['label'].map({'e': 1, 'p': 0})

# Check the quantity of class 0 and class 1
class_counts = df['label'].value_counts()
print(class_counts)
print("class 0:", class_counts[0])
print("class 1:", class_counts[1])

0    3660
1    2104
Name: label, dtype: int64
class 0: 3660
class 1: 2104

In [84]:
df = pd.get_dummies(df, drop_first=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5764 entries, 0 to 5823
Data columns (total 43 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   label                5764 non-null   int64
 1   cap-color-rate       5764 non-null   float64
 2   cap-shape_c          5764 non-null   uint8
 3   cap-shape_f          5764 non-null   uint8
 4   cap-shape_k          5764 non-null   uint8
 5   cap-shape_x          5764 non-null   uint8
 6   cap-surface_g        5764 non-null   uint8
 7   cap-surface_s        5764 non-null   uint8
 8   cap-surface_y        5764 non-null   uint8
 9   bruises_t            5764 non-null   uint8
 10  odor_c               5764 non-null   uint8
 11  odor_f               5764 non-null   uint8
 12  odor_l               5764 non-null   uint8
 13  odor_m               5764 non-null   uint8
 14  odor_n               5764 non-null   uint8
 15  odor_p               5764 non-null   uint8
 16  odor_s               5764 non-null   uint8
 17  odor_y               5764 non-null   uint8
 18  stalk-shape_t        5764 non-null   uint8
 19  ring-number_o        5764 non-null   uint8
 20  ring-number_t        5764 non-null   uint8
 21  ring-type_f          5764 non-null   uint8
 22  ring-type_l          5764 non-null   uint8
 23  ring-type_n          5764 non-null   uint8
 24  ring-type_p          5764 non-null   uint8
 25  spore-print-color_h  5764 non-null   uint8
 26  spore-print-color_k  5764 non-null   uint8
 27  spore-print-color_n  5764 non-null   uint8
 28  spore-print-color_o  5764 non-null   uint8
 29  spore-print-color_r  5764 non-null   uint8
 30  spore-print-color_w  5764 non-null   uint8
 31  spore-print-color_y  5764 non-null   uint8
 32  population_c         5764 non-null   uint8
 33  population_n         5764 non-null   uint8
 34  population_s         5764 non-null   uint8
 35  population_v         5764 non-null   uint8
 36  population_y         5764 non-null   uint8
 37  habitat_g            5764 non-null   uint8
 38  habitat_l            5764 non-null   uint8
 39  habitat_m            5764 non-null   uint8
 40  habitat_p            5764 non-null   uint8
 41  habitat_u            5764 non-null   uint8
 42  habitat_w            5764 non-null   uint8
dtypes: float64(1), int64(1), uint8(41)
memory usage: 365.9 KB

### Train and Test

8. Split train/test with 20% test, stratify, and seed = 2020.

9. Create a Random Forest with GridSearch on training data with 5 CV.

    - ​'criterion':['gini','entropy']
    - 'max_depth': [2,3,6]
    - 'min_samples_leaf':[2,5,10]
    - 'N_estimators':[100,200]
    - 'random_state': 2020

In [85]:
y = df.pop('label')
X = df
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=2020)
print('training set size :', X_train.shape[0])
print('testing set size :', X_test.shape[0])

training set size : 4611
testing set size : 1153

In [86]:
model_rf = GridSearchCV(
    estimator=RandomForestClassifier(),
    param_grid=dict(criterion=['gini','entropy'],
    max_depth=[2,3,6],
    min_samples_leaf=[2,5,10],
    n_estimators=[100,200], 
    random_state=[2020]),
    scoring='f1_weighted',
    cv=5,
    n_jobs=-1
)

In [87]:
model_rf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 6], 'min_samples_leaf': [2, 5, 10],
                         'n_estimators': [100, 200], 'random_state': [2020]},
             scoring='f1_weighted')

In [88]:
print('Best param is')
print(model_rf.best_params_)

Best param is
{'criterion': 'gini', 'max_depth': 6, 'min_samples_leaf': 2, 'n_estimators': 100, 'random_state': 2020}

In [89]:
model_rf = model_rf.best_estimator_

In [90]:
y_pred = model_rf.predict(X_test)

In [91]:
print(classification_report(y_test,y_pred,digits=4))

              precision    recall  f1-score   support

           0     0.9932    0.9986    0.9959       732
           1     0.9976    0.9881    0.9928       421

    accuracy                         0.9948      1153
   macro avg     0.9954    0.9934    0.9944      1153
weighted avg     0.9948    0.9948    0.9948      1153

In [92]:
print(confusion_matrix(y_test,y_pred,labels=[0,1]))

[[731   1]
 [  5 416]]